config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'vegetables#index'
  resources :vegetables do
    member do
      post 'purchase'
    end
    member do
      post "add", to: "favorites#create"
    end
    resources :reviews, only: [:index, :new, :create]
    resources :comments, only: [:create]
    resources :favorites, only: [:index, :destroy, :create]
    # collection do
    #   get 'search'
    # end
  end


    resources :users, only: :show do
    resources :all, only: [:index]
  end
end

app/models/clip.rb
class Clip < ActiveRecord::Base
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :vegetable
  belongs_to :user
  has_one :review
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
	belongs_to :user
	has_many :vegetables
	belongs_to :vegetable_image_id
	# belongs_to :vegetable_image
end

app/models/purchase.rb
class Purchase < ActiveRecord::Base
	belongs_to: user
    belongs_to: vegetable

end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :vegetable
  belongs_to :user
  belongs_to :comment
end

app/models/user.rb
 class User < ActiveRecord::Base
  # validates :nickname, :phone, :email, :password, presence: true
  validates :nickname, :phone_number, presence: true
  has_many :vegetables
  has_many :favorites
  has_many :comments
  has_many :purchases
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :avatar,styles:
  { medium: "300x300#", thumb: "100x100#" }
  validates_attachment_content_type :avatar,
  content_type: ["image/jpg","image/jpeg","image/png"]

end

app/models/vegetable.rb
class Vegetable < ActiveRecord::Base
 belongs_to :user
 has_many :vegetable_images
 has_many :reviews
 has_many :favorites
 has_many :comments
 accepts_nested_attributes_for :vegetable_images
end

app/models/vegetable_image.rb
class VegetableImage < ActiveRecord::Base
  mount_uploader :content, VegetableImageUploader
  belongs_to :vegetable
  has_many :favorites
  # has_many :favorites
  # enum status:{main:0, sub:1}
end

app/controllers/all_controller.rb
class AllController < ApplicationController
  def index
 @vegetable = User.find(params[:user_id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment =Comment.create(text: comment_params[:text], vegetable_id: comment_params[:vegetable_id], user_id: current_user.id)
    redirect_to "/vegetables/#{@comment.vegetable.id}"
  end

  def comment_params
    params.permit(:text, :vegetable_id)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
 def create
 	vegetable = Vegetable.find(params[:id])
 	images = vegetable.vegetable_images
 	main_image = images.where(status: 0).first
 	

 	# favorite = Favorite.new(create_params)

 	# favorite.save
  	Favorite.create(
 		user_id: current_user.id,
 		vegetable_id: params[:id],
 		# vegetable_image: main_image.id
	)

 end

  def destroy
    @favorite = Favorite.find(params[:id])
    if @favorite.destroy
      redirect_to user_path(current_user)
    end
 end

 private
 def create_params
 	# params.permit(:id)
 	# params.require(:favorite).merge(
 	# 	user_id: current_user.id,
 	# 	vegetable_id: params[:id],
 	# 	vegetable_image: 
 	# )
 end
end

app/controllers/ranking_controller.rb
class RankingController < ApplicationController
	# def index
	# 	binding.pry
	# 	reviews = Review.group(:vegetable_id).sum(:general_rate)
	# 	divisors = Review.group(:vegetable_id).count
	# 	rankings = []


	# 	@ranking = reviews.each do |index, review|
	# 		if divisors[index].present?
	# 			ranking = review / divisors[index]
	# 			rankings.push(ranking)
	# 		end
	# 	end
	# 	vegetables = Review.group(:vegetable_id)

	# end
end
  # .order('count_general_rate DESC').limit(10).count(:general_rates).keys
  #     @ranking = vegetable_ids.map { |id| Vegetable.find(id) }

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  # before_action :authenticate_user!, only: :new
  def new
   @vegetable = Vegetable.find(params[:vegetable_id])
   @review = Review.new
  end

  def create
    Review.create(create_params)
    redirect_to controller: :vegetables, action: :index
  end

  private
  def create_params
    params.require(:review).permit(:general_rate, :taste_rate, :visual_rate, :communication_rate).merge(vegetable_id: params[:vegetable_id], comment_id: params[:comment_id], user_id: params[:user_id] )
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    user = User.find(params[:id])
    @vegetables = user.vegetables.order('id ASC').limit(5)
    @favorites = user.favorites
  end
end

app/controllers/vegetables_controller.rb
class VegetablesController < RankingController


  def index
    @vegetables = Vegetable.order('id ASC').limit(10)

  end



  def new
  @vegetable = Vegetable.new
  4.times{ @vegetable.vegetable_images.build }

  end

  def create
  
     Vegetable.create(vegetables_params)

  end

  def show
  @vegetable = Vegetable.find(params[:id])
  @comments = @vegetable.comments.includes(:user)
      # @vegetable_image = Vegetable_image.find(params[:vegetable_id])
  end



  def purchase
     Payjp.api_key = PYAJP_SECRET_KEY
     @price = Vegetable.find(params[:id])
     Payjp::Charge.create(
      :amount => @price.price,
      :card => params['payjp-token'],
      :currency => 'jpy'
      )
  end

  private
 def vegetables_params
  params.require(:vegetable).permit(:name, :price, :description, :user_id,
                                    {vegetable_images_attributes: [:content, :status]})
 end

 def search
 @vegetable =Vegetable.where('name LIKE(?)', "%#{params[:keyword]}%").limit(20)
 end
end

app/helpers/all_helper.rb
module AllHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/ranking_helper.rb
module RankingHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vegetables_helper.rb
module VegetablesHelper
end

app/views/favorites/create.html.erb
お気に入りしました

app/views/users/show.html.erb
<div class="sell_page"
   <h2><%= current_user.nickname %>
     <span class="my_icon">さんのマイページ</span>
   </h2>
    <header class="user_page-header">
      <%= image_tag current_user.avatar, class: "my_icon"%>
        <div class="my_vegetables">出品中の商品</div>
      <%= link_to "商品一覧",'/users/:user_id/all'%>
    </header>
      <div class="my_list">
        <div class="my_leftlist">

          <% @vegetables.each do |vegetable|%>
            <div class="user_vegetables">
              <%= simple_format(vegetable.description) %>
                <span class="name clearfix">
                 <a href="/vegetables/<%= vegetable.id %>"> <%= vegetable.name %></a>
                </span>
            </div>

            <% vegetable.vegetable_images.each do |image|%>
              <% if image.status == 0 %>
                <div class="my_vegetable_list"><%= image_tag image.content, class: 'user_vegetables' %>
                </div>
               <% end %>
             <% end %>

             <% end -%>
        <div>
          <% @favorites.each do |favorite|%>
            <div class="user_vegetables">
                <span class="name clearfix">
                 <a href= vegetable_path > <%= favorite.vegetables.name %></a>
                </span>
            </div>
               <% @favorites.each do |favorite|%>
                  <%if favorite.user_id == current_user.id && favorite.vegetable_images.status == 0%>


                   <a href="/vegetables/<%= @vegetables.id %>"> <%= favorite.name %></a>
                     <%= favorite.vegetable_images.content %>
                   <% end -%>
              <% end %>
           <% end %>
            </div>
         </div>
      </div>
</div>