config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'vegetables#index'
  resources :vegetables do
    member do
      post 'purchase'
    end
    member do
      post "add", to: "favorites#create"
    end
    resources :reviews, only: [:index, :new, :create]
    resources :comments, only: [:create]
    resources :favorites, only: [:index, :destroy, :create]
    # collection do
    #   get 'search'
    # end
  end


    resources :users, only: :show do
    resources :all, only: [:index]
  end
end

app/models/clip.rb
class Clip < ActiveRecord::Base
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :vegetable
  belongs_to :user
  has_one :review
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
	belongs_to :user
	has_many :vegetables
	belongs_to :vegetable_image_id
	# belongs_to :vegetable_image
end

app/models/purchase.rb
class Purchase < ActiveRecord::Base
	belongs_to: user
    belongs_to: vegetable

end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :vegetable
  belongs_to :user
  belongs_to :comment
end

app/models/user.rb
 class User < ActiveRecord::Base
  # validates :nickname, :phone, :email, :password, presence: true
  validates :nickname, :phone_number, presence: true
  has_many :vegetables
  has_many :favorites
  has_many :comments
  has_many :purchases
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :avatar,styles:
  { medium: "300x300#", thumb: "100x100#" }
  validates_attachment_content_type :avatar,
  content_type: ["image/jpg","image/jpeg","image/png"]

end

app/models/vegetable.rb
class Vegetable < ActiveRecord::Base
 belongs_to :user
 has_many :vegetable_images
 has_many :reviews
 has_many :favorites
 has_many :comments
 accepts_nested_attributes_for :vegetable_images
end

app/models/vegetable_image.rb
class VegetableImage < ActiveRecord::Base
  mount_uploader :content, VegetableImageUploader
  belongs_to :vegetable
  has_many :favorites
  # has_many :favorites
  # enum status:{main:0, sub:1}
end

app/controllers/all_controller.rb
class AllController < ApplicationController
  def index
 @vegetable = User.find(params[:user_id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment =Comment.create(text: comment_params[:text], vegetable_id: comment_params[:vegetable_id], user_id: current_user.id)
    redirect_to "/vegetables/#{@comment.vegetable.id}"
  end

  def comment_params
    params.permit(:text, :vegetable_id)
  end
end

app/controllers/ranking_controller.rb
class RankingController < ApplicationController
	# def index
	# 	binding.pry
	# 	reviews = Review.group(:vegetable_id).sum(:general_rate)
	# 	divisors = Review.group(:vegetable_id).count
	# 	rankings = []


	# 	@ranking = reviews.each do |index, review|
	# 		if divisors[index].present?
	# 			ranking = review / divisors[index]
	# 			rankings.push(ranking)
	# 		end
	# 	end
	# 	vegetables = Review.group(:vegetable_id)

	# end
end
  # .order('count_general_rate DESC').limit(10).count(:general_rates).keys
  #     @ranking = vegetable_ids.map { |id| Vegetable.find(id) }

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  # before_action :authenticate_user!, only: :new
  def new
   @vegetable = Vegetable.find(params[:vegetable_id])
   @review = Review.new
  end

  def create
    Review.create(create_params)
    redirect_to controller: :vegetables, action: :index
  end

  private
  def create_params
    params.require(:review).permit(:general_rate, :taste_rate, :visual_rate, :communication_rate).merge(vegetable_id: params[:vegetable_id], comment_id: params[:comment_id], user_id: params[:user_id] )
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    user = User.find(params[:id])
    @vegetables = user.vegetables.order('id ASC').limit(5)
    @favorites = user.favorites
  end
end

app/controllers/vegetables_controller.rb
class VegetablesController < RankingController


  def index
    @vegetables = Vegetable.order('id ASC').limit(10)

  end



  def new
  @vegetable = Vegetable.new
  4.times{ @vegetable.vegetable_images.build }

  end

  def create
  
     Vegetable.create(vegetables_params)

  end

  def show
  @vegetable = Vegetable.find(params[:id])
  @comments = @vegetable.comments.includes(:user)
      # @vegetable_image = Vegetable_image.find(params[:vegetable_id])
  end



  def purchase
     Payjp.api_key = PYAJP_SECRET_KEY
     @price = Vegetable.find(params[:id])
     Payjp::Charge.create(
      :amount => @price.price,
      :card => params['payjp-token'],
      :currency => 'jpy'
      )
  end

  private
 def vegetables_params
  params.require(:vegetable).permit(:name, :price, :description, :user_id,
                                    {vegetable_images_attributes: [:content, :status]})
 end

 def search
 @vegetable =Vegetable.where('name LIKE(?)', "%#{params[:keyword]}%").limit(20)
 end
end

app/helpers/all_helper.rb
module AllHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/ranking_helper.rb
module RankingHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vegetables_helper.rb
module VegetablesHelper
end

app/views/vegetables/all.html.erb
<div class="my_vegetable_lsit">
<% @vegetable.vegetable_images.each do |image| %>
 <%= image_tag image.image, class: 'user_vegetables' %>
<% end %>
</div>

app/views/vegetables/create.html.erb
<div class="created">出品が完了しました！　うまくできているかマイページから確認してみましょう</div>

app/views/vegetables/favorite.html.erb
お気に入りしました

app/views/vegetables/index.html.erb
<div class="introduce1">
   <h2 class="explaine1">ネット販売だからこそ<br>
   最高品質をあなたのもとに</h2>
</div>

<div class="hoge clearfix">
  <div class="introduce2">
    <div class="explaine2" ><%= image_tag 'introduce2.jpg' %>
      <p><%="ご注文の商品は翌日の収穫直後に配送"%></p>
    </div>
  </div>
  <div class="introduce3">
    <div class="explaine3" >
      <%= image_tag 'introduce3.jpg' %>
      <p>弊社スタッフが出品農家を独自の基準で審査。<br>厳選された農家のみが出品しているので安全・安心です</p>
    </div>
  </div>

  <div class="introduce4">
    <div class="explaine4" >
      <%= image_tag 'introduce4.jpg' %>
      <p><%="各商品ページには４枚以上の写真が乗っており、他にはないレビューシステムを導入しております。味の詳細や特徴が一目でわかります"%></p>
    </div>
  </div>
</div>

<div class="contents_row">


<!-- ランキング表示 -->
<!-- 新着商品 -->
<div class="pickup">新着商品</div>
<% @vegetables.each do |vegetable| %>
                  <div class="col">
                    <a href="/vegetables/<%= vegetable.id %>"></a>
                      <h3 class="text-xsmall text-overflow" title="<vegetable.name>"><a href="/vegetables/<%= vegetable.id %>">
                      <%= vegetable.name%>
                      </h3>
                      <p class="text-small">
                        <%if vegetable.reviews.present?%>
                        <!-- <span class="rating-star">

                        <%%> -->
                       <span class="rate rate-<%= vegetable.reviews.general_rate %>"></span>
                        <% end %>
                      </p>




                  <% vegetable.vegetable_images.each do |image| %>
         <% if image.status == 0 %>
           <div class="my_vegetable_list">
            <%= image_tag image.content, class: 'user_vegetables' %>
           </div>
         <% end %>
       <% end %>
   <% end %>
 </div>

 <div class="new_vegetable">新着商品</div>
</div>

app/views/vegetables/new.html.erb
<div class="sell_page">
  <%= form_for @vegetable do |f| %>
  <div class="sell_frame">
    <%f.label :name%> 商品名<br>
    <%=f.text_field :name,  style: 'width: 340px;height: 20px;',placeholder: '商品名で美味しさをアピール！'%>
  </div>

<div class="sell_advice">
  <div class="photo_area"><%=f.label:写真%>
    <div style="font-size: 10px; margin-top: 5px;">
    </div>
  </div>
    写真は４枚載せてください<br>写真撮影はできるだけ太陽光を当てて撮ると美味しさが引き立ちます！
</div>
<div class="field">

<div class="status">

<%= f.fields_for :vegetable_images do |image| %>
    <%= image.file_field :content %>
    <%= image.hidden_field  :status, value: image.index %>
</div>
<% end %>


</div>
  <div class="sell_frame" >
  <%f.label :price%> 価格<br>
    <%=f.text_field :price,  style: 'width: 340px;height: 20px;',placeholder: '(例)1000'%>

  <div class="sell_detail">
  <%=f.label:商品説明%>
  <div style="font-size: 10px; margin-top: 5px;">
    特徴やこだわりなど、自慢の商品をアピールしましょう！
  </div>
  <%=f.text_area  :description, placeholder: '(例)屋内の清潔な農場でで耕栽培していますので、菌類・害虫・汚染物質の付着が殆どなく、安心して食べて頂けます。！' %>' %>

  <%= f.hidden_field :user_id, value: current_user.id %>

  </div>
    <div class="col10">

      <%= button_tag type: "submit" ,value:"出品を完了する", class: "sell_submit" do %>出品を完了する
      <i class="icon-arrow-right"></i>
       </div>
      <% end %>
  <%end%>


</div>

app/views/vegetables/purchase.html.erb
支払いが完了しました

app/views/vegetables/show.html.erb
<div class="vegetable_page">
  <div class="vegetable_name"> <%= @vegetable.name %></div>
  <div class="my_vegetable_list">
   <% @vegetable.vegetable_images.each do |image| %>
   <%= image_tag image.content, class: 'user_vegetables' %>
   <% end %>
</div>


<table class="sell_table" border="1">
  <tr >
    <td class="seller_nickname1">出品農家</td>
    <td class="seller_nickname2"><%= @vegetable.user.nickname %></td>
  </tr>
  <tr>
    <td  class="detail_text1">商品の特徴・<br>こだわり</td>
    <td  class="detail_text2"><%=@vegetable.description %></td>
  </tr>
  <tr>
  <td class="seller_nickname1">価格</td>
    <td class="seller_nickname2"><%= @vegetable.price %></td>
    </tr>
</table>
 <a  class='post_review' href="/vegetables/<%=@vegetable.id%>/reviews/new">レビューを投稿する</a>

      <div>
       <%= link_to "この野菜をお気に入り", add_vegetable_path, method: :post %>
      </div>
      <div class="container">

    <!-- ここからフォーム -->

  </div>

<div class="reviews">
 <% @vegetable.reviews.each do |review| %>
   <h3 class="text-xsmall text-overflow" title="<%= review.nickname %>">
      <%= review.nickname %>さんの書いたレビュー
   </h3>
      <p class="text-small">
        <span class="rating-star"><i class="star-actived rate-[ここに評価を表示]0"></i></span>
      </p>
      <p>総合評価　　　
       <span class="rate rate<%= review.general_rate %>"></span>

      </p>
      <p>味の納得感　　
      <span class="rate rate<%= review.taste_rate %>"></span>
       </p>
      <p>見た目の正確さ
      <span class="rate rate<%= review.visual_rate %>"></span>
      </p>
      <p>出品農家の対応
      <span class="rate rate<%= review.communication_rate %>"></span>
      </p>
      <p>購入した感想<br>
        <%= review.comment %>
      </p>
 <% end %>
</div>
<%= form_tag(action: :purchase, method: :post) do %>
  <script type="text/javascript" src="https://checkout.pay.jp" class="payjp-button" data-key="<%=  PYAJP_PUBLIC_KEY%>"></script>
<% end %>

 <% if current_user %>
      <%= form_tag("/vegetables/#{@vegetable.id}/comments", method: :post) do %>
        <textarea cols="30" name="text" placeholder="コメントする" rows="2"></textarea>
        <input type="submit" value="SENT">
      <% end %>
    <% end %>
<div class="comments">
      <h4>＜コメント一覧＞</h4>
      <% if @comments %>
        <% @comments.each do |comment| %>
          <p>
            <strong><%= link_to comment.user.nickname, "/users/#{comment.user_id}" %>：</strong>
            <%= comment.text %>
          </p>
        <% end %>
      <% end %>
    </div>

</div>