config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'vegetables#index'
  resources :vegetables do
    member do
      post 'purchase'
    end
    member do
      post "add", to: "favorites#create"
    end
    resources :reviews, only: [:index, :new, :create]
    resources :comments, only: [:create]
    resources :favorites, only: [:index, :destroy, :create]
    # collection do
    #   get 'search'
    # end
  end


    resources :users, only: :show do
    resources :all, only: [:index]
  end
end

app/models/clip.rb
class Clip < ActiveRecord::Base
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :vegetable
  belongs_to :user
  has_one :review
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
	belongs_to :user
	has_many :vegetables
	belongs_to :vegetable_image_id
	# belongs_to :vegetable_image
end

app/models/purchase.rb
class Purchase < ActiveRecord::Base
	belongs_to: user
    belongs_to: vegetable

end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :vegetable
  belongs_to :user
  belongs_to :comment
end

app/models/user.rb
 class User < ActiveRecord::Base
  # validates :nickname, :phone, :email, :password, presence: true
  validates :nickname, :phone_number, presence: true
  has_many :vegetables
  has_many :favorites
  has_many :comments
  has_many :purchases
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :avatar,styles:
  { medium: "300x300#", thumb: "100x100#" }
  validates_attachment_content_type :avatar,
  content_type: ["image/jpg","image/jpeg","image/png"]

end

app/models/vegetable.rb
class Vegetable < ActiveRecord::Base
 belongs_to :user
 has_many :vegetable_images
 has_many :reviews
 has_many :favorites
 has_many :comments
 accepts_nested_attributes_for :vegetable_images
end

app/models/vegetable_image.rb
class VegetableImage < ActiveRecord::Base
  mount_uploader :content, VegetableImageUploader
  belongs_to :vegetable
  has_many :favorites
  # has_many :favorites
  # enum status:{main:0, sub:1}
end

app/controllers/all_controller.rb
class AllController < ApplicationController
  def index
 @vegetable = User.find(params[:user_id])
  end
end

app/controllers/ranking_controller.rb
class RankingController < ApplicationController
	# def index
	# 	binding.pry
	# 	reviews = Review.group(:vegetable_id).sum(:general_rate)
	# 	divisors = Review.group(:vegetable_id).count
	# 	rankings = []


	# 	@ranking = reviews.each do |index, review|
	# 		if divisors[index].present?
	# 			ranking = review / divisors[index]
	# 			rankings.push(ranking)
	# 		end
	# 	end
	# 	vegetables = Review.group(:vegetable_id)

	# end
end
  # .order('count_general_rate DESC').limit(10).count(:general_rates).keys
  #     @ranking = vegetable_ids.map { |id| Vegetable.find(id) }

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  # before_action :authenticate_user!, only: :new
  def new
   @vegetable = Vegetable.find(params[:vegetable_id])
   @review = Review.new
  end

  def create
    Review.create(create_params)
    redirect_to controller: :vegetables, action: :index
  end

  private
  def create_params
    params.require(:review).permit(:general_rate, :taste_rate, :visual_rate, :communication_rate).merge(vegetable_id: params[:vegetable_id], comment_id: params[:comment_id], user_id: params[:user_id] )
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    user = User.find(params[:id])
    @vegetables = user.vegetables.order('id ASC').limit(5)
    @favorites = user.favorites
  end
end

app/helpers/all_helper.rb
module AllHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/ranking_helper.rb
module RankingHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vegetables_helper.rb
module VegetablesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Air Agri</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <script type="text/javascript">
      WebFontConfig = {
        google: { families: [ 'Unica+One::latin' ] }
      };
      (function() {
        var wf = document.createElement('script');
        wf.src = ('https:' == document.location.protocol ? 'https' : 'http') +
          '://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js';
        wf.type = 'text/javascript';
        wf.async = 'true';
        var s = document.getElementsByTagName('script')[0];
        s.parentNode.insertBefore(wf, s);
      })();
    </script>
  </head>

 <body class="body">
<header>
    <h1 class="grid-6" ><a class="title" href="/">Air Agri</a>



<% if user_signed_in? %>

 <div class="user_nav ">
    <div class="user__info">
     <a class = 'get'href="/users/<%= current_user.id %>">マイページ</a>
      </div>
        <div class="user__info" style type="text/css">
        <%= link_to "ログアウト", destroy_user_session_path ,method: :delete ,class: 'get'%>
        </div>
        <div class="user__info">
        <%= link_to "出品する", new_vegetable_path,class: 'get' %>
         </div>


          </div>
          <div class="nickname">ようこそ<%= current_user.nickname%>さん</div>

<% else %>
   <div class="user__info">
    <%= link_to "ログイン", new_user_session_path, class: 'post'%>
     </div>
      <div class="user__info"><%= link_to "新規会員登録", new_user_registration_path,class: 'post' %>
   </div>

<% end %>
</h1>
</header>


    <%= yield %>

    <footer class="clearfix">

        Copyright Air Agri 2017.

    </footer>
  </body>
</html>